import React from 'react';
import {Button, StyleSheet, Text, View} from 'react-native';
import {
  responsiveHeight,
  responsiveWidth,
  responsiveFontSize,
  responsiveScreenHeight,
  responsiveScreenFontSize,
  responsiveScreenWidth,
} from 'react-native-responsive-dimensions';
import {colors, fontFamily} from '../../../Services';
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  header: {
    width: responsiveWidth(100),
    alignSelf: 'center',
    justifyContent: 'space-between',
    paddingLeft: responsiveWidth(8),
    alignItems: 'center',
    flexDirection: 'row',
    height: responsiveHeight(10),
    paddingRight: responsiveWidth(5),
  },
  headerTitle: {
    color: colors.black,
    fontSize: responsiveFontSize(2.3),
    width: responsiveWidth(60),
    fontFamily: fontFamily.extraBold,
  },
  infobtn: {
    resizeMode: 'contain',
    height: responsiveHeight(4),
    width: responsiveWidth(8),
  },
  blurImage: {
    width: responsiveWidth(100),
    height: responsiveHeight(30),
    resizeMode: 'cover',
  },
  blurImage2: {
    width: responsiveWidth(65),
    height: responsiveHeight(30),
    resizeMode: 'cover',
    alignSelf:'center'
  },
  home2: {
    width: responsiveWidth(50),
    height: responsiveHeight(30),
    // resizeMode: 'contain',
    alignSelf: 'center',
  },
  TitleView: {
    backgroundColor: colors.splash,
    borderRadius: responsiveWidth(1),
    paddingVertical:responsiveHeight(0.5),
    paddingHorizontal:responsiveHeight(0.7),
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    color: colors.white,
    fontFamily: fontFamily.bold,
    fontSize: responsiveFontSize(2),
  },
  boldtext: {
    color: colors.black,
    fontFamily: fontFamily.extraBold,
    fontSize: responsiveFontSize(3.3),
    marginTop: responsiveHeight(3),
    marginHorizontal: responsiveWidth(4),
  },
  wrapper: {
    alignSelf: 'flex-start',
  },
  boldheading: {
    marginLeft: responsiveWidth(5),
    fontFamily: fontFamily.bold,
    marginTop: responsiveHeight(0.5),
    color: colors.black,
    fontSize: responsiveFontSize(3.5),
    marginBottom: responsiveHeight(2),
  },
  RowView1: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: responsiveWidth(2),
    width: responsiveWidth(31),
    // height: responsiveHeight(3),
    alignItems: 'center',
    marginTop: responsiveHeight(2),
    marginLeft: responsiveWidth(5),
  },
  date: {
    color: colors.black,
    marginLeft: responsiveWidth(3),
    width: responsiveWidth(60),
    fontFamily: fontFamily.semiBold,
    fontSize: responsiveFontSize(2),
  },
  iconSmall: {
    resizeMode: 'contain',
    height: responsiveFontSize(3),
    width: responsiveFontSize(3),
  },
  mediumHeading: {
    fontFamily: fontFamily.bold,
    marginTop: responsiveHeight(4),
    color: colors.black,
    fontSize: responsiveFontSize(2.5),
    marginBottom: responsiveHeight(1),
    paddingLeft: responsiveWidth(5),
  },
  mediumHeading2: {
    fontFamily: fontFamily.bold,
    marginTop: responsiveHeight(2),
    color: colors.black,
    fontSize: responsiveFontSize(2.5),
    paddingLeft: responsiveWidth(5),
    marginBottom: responsiveHeight(2),
  },
  regular: {
    color: colors.black,
    fontSize: responsiveFontSize(1.8),
    fontFamily: fontFamily.medium,
    paddingHorizontal: responsiveWidth(5),
  },
  FlatListMainView: {
    marginVertical: responsiveHeight(1.5),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: responsiveWidth(5),
  },
  FlatListMainView2: {
    marginVertical: responsiveHeight(2),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: responsiveWidth(5),
  },
  text2: {
    color: colors.greyText,
    marginLeft: responsiveWidth(1),
    fontFamily: fontFamily.semiBold,
    fontSize: responsiveFontSize(1.6),
  },
  text1: {
    color: colors.royal,
    fontSize: responsiveFontSize(1.8),
    fontFamily: fontFamily.semiBold,
  },
  cont: {
    flexDirection: 'row',
    marginTop: responsiveHeight(0.5),
  },
  FLWrapper: {
    backgroundColor: 'rgba(232, 233, 236, 0.2)',
    marginTop: responsiveHeight(2),
    width: responsiveWidth(100),
  },
  bottomView: {
    backgroundColor: 'white',
    bottom: responsiveHeight(2),
  },
  line: {
    width: responsiveWidth(100),
    height: responsiveHeight(0.2),
    backgroundColor: colors.border + '30',
  },
  silverView: {
    width: responsiveWidth(100),
    backgroundColor: colors.silver + '40',
    paddingVertical: responsiveHeight(2),
    paddingLeft: responsiveWidth(5),
    paddingRight: responsiveWidth(10),
    marginTop: responsiveHeight(3.5),
  },
  sessionsSilverView: {
    width: responsiveWidth(100),
    backgroundColor: colors.silver + '40',
    paddingVertical: responsiveHeight(2),
  },
  ResourceFlatListBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    marginVertical: responsiveHeight(0.8),
    paddingLeft: 10,
    width: '100%',
    height: responsiveWidth(25),
    alignSelf: 'center',
  },
  FlatListBtn: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  FlatListTitle: {
    color: colors.royal,
    fontFamily: fontFamily.bold,
    fontSize: responsiveFontSize(2.1),
    marginTop: 10,
  },
  FlatListSubtitle: {
    color: colors.royal,
    fontFamily: fontFamily.bold,
    fontSize: responsiveFontSize(1.8),
  },
  ResourceFlatListTitle: {
    color: colors.black,
    fontFamily: fontFamily.bold,
    fontSize: responsiveFontSize(2.1),
    marginLeft: 10
  },
  FlatListDate: {
    width: responsiveWidth(50),
    color: colors.black,
    marginLeft: responsiveWidth(1),
    fontSize: responsiveFontSize(1.8),
    fontFamily: fontFamily.regular,
  },
  bottomView: {
    position: 'absolute',
    bottom: 0,
    backgroundColor: colors.white,
    height: responsiveHeight(10),
  },

  FLheader: {
    fontFamily: fontFamily.bold,
    color: colors.black,
    fontSize: responsiveFontSize(2.5),
    marginBottom: responsiveHeight(2),
  },
  dollarView: {
    paddingVertical:responsiveHeight(0.5),
    paddingHorizontal:responsiveHeight(0.7),
    borderRadius: responsiveWidth(1),
    backgroundColor: colors.royal,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: responsiveWidth(1),
  },
  dollarText: {
    color: colors.white,
    fontFamily: fontFamily.bold,
    fontSize: responsiveFontSize(2),
  },
  Freeview: {
    paddingVertical:responsiveHeight(0.5),
    paddingHorizontal:responsiveHeight(0.7),
    borderRadius: responsiveWidth(1),
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: responsiveWidth(1),
  },
  FreeText: {
    color: colors.royal,
    fontFamily: fontFamily.bold,
    fontSize: responsiveFontSize(1.8),
  },
  RowView2: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    width: responsiveScreenWidth(35),
    marginTop: responsiveHeight(15),
    marginLeft: 10,
    position: 'absolute',
    bottom: responsiveHeight(2),
  },
  dateText: {
    color: colors.greyText,
    fontFamily: fontFamily.bold,
    fontSize: responsiveFontSize(1.8),
    marginVertical: responsiveHeight(2),
    marginLeft: responsiveWidth(5)
  },
  locationView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  mediumHeading01: {
    fontFamily: fontFamily.bold,
    color: colors.royal,
    fontSize: responsiveFontSize(2.2),
    marginLeft: responsiveWidth(1),
  },
  mediumHeading012: {
    fontFamily: fontFamily.bold,
    color: colors.black,
    fontSize: responsiveFontSize(2.5),
  },
  scheduleView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: responsiveHeight(4),
  },
  speaker: {
    width: responsiveWidth(50),
    color: colors.black,
    marginLeft: responsiveWidth(1),
    fontSize: responsiveFontSize(1.8),
    fontFamily: fontFamily.bold,
  },
  line1: {
    width: responsiveWidth(100),
    height: responsiveHeight(0.2),
    backgroundColor: colors.border + '30',
    marginTop: responsiveHeight(1.5),
    marginBottom: responsiveHeight(2),
  },
  iconSmall1: {
    resizeMode: 'contain',
    height: responsiveFontSize(2.7),
    width: responsiveFontSize(2.7),
  },
  TitleView1: {
    backgroundColor: colors.green,
    borderRadius: responsiveWidth(1),
    paddingVertical:responsiveHeight(0.5),
    paddingHorizontal:responsiveHeight(0.7),
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: responsiveWidth(1),
  },
  notRegisteredView: {
    backgroundColor: colors.white,
    borderRadius: responsiveWidth(1),
    paddingVertical:responsiveHeight(0.5),
    paddingHorizontal:responsiveHeight(0.7),
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: responsiveWidth(1),
  },
  absolute: {
    position: "absolute",
    top: 0,
    left: 0,
    bottom: 0,
    right: 0
  }
});
